[package]
name = "efmt"
version = "0.0.6"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Erlang code formatter"
homepage = "https://github.com/sile/efmt"
repository = "https://github.com/sile/efmt"
readme = "README.md"

[dependencies]
anyhow = "1"
console = "0.15"
erl_tokenize = "0.4"
efmt_derive = { path = "efmt_derive", version = "0.0.2" }
env_logger = "0.9"
glob = "0.3"
log = "0.4"
sha256 = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
similar = { version= "2", features = ["inline"] }
structopt = "0.3"
tempfile = "3"
thiserror = "1"
pprof = {version="0.4", features = ["flamegraph"], optional=true}

[dev-dependencies]
indoc = "1"
similar-asserts = "1"

[workspace]
members = ["efmt_derive"]
