[package]
name = "efmt"
version = "0.0.1"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
erl_tokenize = "0.4"
log = "0.4"
structopt = "0.3"
thiserror = "1"
