[package]
name = "efmt"
version = "0.0.1"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Erlang code formatter"
homepage = "https://github.com/sile/efmt"
repository = "https://github.com/sile/efmt"
readme = "README.md"

[dependencies]
anyhow = "1"
erl_tokenize = "0.4"
efmt_derive = { path = "efmt_derive", version = "0.0.1" }
log = "0.4"
structopt = "0.3"
thiserror = "1"

[dev-dependencies]
indoc = "1"

[workspace]
members = ["efmt_derive"]
